name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for pre-release (e.g., v1.0.0-beta.1)'
        required: true
        default: 'v1.0.0-dev'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run make
      run: make
    
    - name: Create ZIP package
      run: |
        # Create the plugin directory with the correct name
        mkdir -p ./fylr-plugin-3d-specimen-viewer
        
        # Copy files using rsync, excluding unnecessary directories
        rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='fylr-plugin-3d-specimen-viewer' . ./fylr-plugin-3d-specimen-viewer/
        
        # Create the ZIP file from within the parent directory to avoid path issues
        cd fylr-plugin-3d-specimen-viewer
        zip -r ../fylr-plugin-3d-specimen-viewer.zip .
        cd ..

    - name: Get version
      id: get_version
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        else
          VERSION="${{ github.event.inputs.version }}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: ${{ github.event_name == 'workflow_dispatch' }}
        generate_release_notes: true
        files: |
          fylr-plugin-3d-specimen-viewer.zip
        body: |
          ## 3D Specimen Viewer Plugin Release ${{ steps.get_version.outputs.version }}
          
          This release contains the fylr 3D Specimen Viewer Plugin.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ## 3D Specimen Viewer Plugin Release ${{ steps.get_version.outputs.version }}
          
          This release contains the fylr 3D Specimen Viewer Plugin.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
